"""counter

Revision ID: 1d5e843ca4a8
Revises: 80c6070c9b23
Create Date: 2024-10-29 00:02:40.469336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5e843ca4a8'
down_revision: Union[str, None] = '80c6070c9b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paids',
    sa.Column('count', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('count')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paids')
    # ### end Alembic commands ###
