"""counteredit

Revision ID: 6786f1419858
Revises: 1d5e843ca4a8
Create Date: 2024-10-29 00:04:28.692705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6786f1419858'
down_revision: Union[str, None] = '1d5e843ca4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paids',
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('count')
    )
    # ### end Alembic commands ###
