"""empty message

Revision ID: 80c6070c9b23
Revises: 379f2a2a69a1
Create Date: 2024-10-28 23:09:10.994825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c6070c9b23'
down_revision: Union[str, None] = '379f2a2a69a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_payment_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_payment_requested')
    # ### end Alembic commands ###
