"""paids table

Revision ID: c335ffb36eac
Revises: 6786f1419858
Create Date: 2024-10-29 00:06:06.160235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c335ffb36eac'
down_revision: Union[str, None] = '6786f1419858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paids')
    # ### end Alembic commands ###
